export enum Routes {
  //App
  AUTH_NAVIGATOR = 'AUTH_NAVIGATOR',
  TABS_NAVIGATOR = 'TABS_NAVIGATOR',

  //TABS
  PROJECT_NAVIGATOR = 'PROJECT_NAVIGATOR',
  TASK_NAVIGATOR = 'ROOM_NAVIGATOR',
  USER_NAVIGATOR = 'USER_NAVIGATOR',

  //AUTH
  SIGN_IN = 'SIGN_IN',
  SIGN_UP = 'SIGN_UP',

  //PROFILE
  USER_DETAIL = 'USER_DETAIL',
}
