export enum Routes {
  //App
  AUTH_NAVIGATOR = 'AUTH_NAVIGATOR',
  TABS_NAVIGATOR = 'TABS_NAVIGATOR',

  //TABS
  PROJECT_NAVIGATOR = 'PROJECT_NAVIGATOR',
  TASK_NAVIGATOR = 'ROOM_NAVIGATOR',
  USER_NAVIGATOR = 'USER_NAVIGATOR',

  //AUTH
  SIGN_IN = 'SIGN_IN',
  SIGN_UP = 'SIGN_UP',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',

  //PROJECT
  PROJECT_LIST = 'PROJECT_LIST',
  PROJECT_DETAIL = 'PROJECT_DETAIL',
  PROJECT_FORM = 'PROJECT_CREATE',

  //TASK
  TASK_LIST = 'TASK_LIST',
  TASK_DETAIL = 'TASK_DETAIL',
  TASK_FORM = 'TASK_FORM',

  //USER
  USER_DETAIL = 'USER_DETAIL',
  USER_UPDATE = 'USER_UPDATE',
}
